# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeoulHotPle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeoulHotPle

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'GooglePlaces', '~> 2.1.1'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  
  # chatting
  pod 'JSQMessagesViewController'

  # google map
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.1'
  pod 'GoogleMaps'

end
